package com.chitchat.client.components.gui;

import com.chitchat.components.net.*;
import com.chitchat.components.user.*;

import utilx.Prompt;

public class CreateAccountForm extends ChitChatPanel {
    private static final int WIDTH = 350;
    private static final int HEIGHT = 205;

    private final MainGUI parent;
    /**
     * Creates new form CreateAccountForm
     *
     * @param objParent The parent, a <code>MainGUI</code>
     */
    public CreateAccountForm(MainGUI objParent) {
        initComponents();
        this.parent = objParent;
    }

    /**
    * Gets the desired width of this panel
    *
    * @return The desired width
    */
    public int getWidth()
    {
        return CreateAccountForm.WIDTH;
    }

    /**
    * Gets the desired height of this panel
    *
    * @return The desired height
    */
    public int getHeight()
    {
        return CreateAccountForm.HEIGHT;
    }

    /** An event fired when the panel is shown */
    public void onShow()
    {
        this.jUsername.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInfoLabel = new javax.swing.JLabel();
        jChitChatLogo = new javax.swing.JLabel();
        jUsernameLabel = new javax.swing.JLabel();
        jPasswordLabel = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jUsername = new javax.swing.JTextField();
        jConfirmPassLabel = new javax.swing.JLabel();
        jConfirmPassword = new javax.swing.JPasswordField();
        jCreateAccountButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(357, 160));

        jInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jInfoLabel.setText("Please enter new account details");

        jChitChatLogo.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jChitChatLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jChitChatLogo.setText("chit chat");

        jUsernameLabel.setText("Username");

        jPasswordLabel.setText("Password");

        jConfirmPassLabel.setText("Password");

        jCreateAccountButton.setText("Create Account");
        jCreateAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jChitChatLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jInfoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addComponent(jUsername)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jConfirmPassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jCreateAccountButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jChitChatLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jConfirmPassLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCreateAccountButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCreateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateAccountButtonActionPerformed
        String strUsername = this.jUsername.getText();
        String strPass = new String(this.jPassword.getPassword());
        String strConfirm = new String(this.jConfirmPassword.getPassword());

        if(strUsername.length() < 3)
        {
            Prompt.showError("Username must be >= 3 characters");
            this.jUsername.requestFocus();
        }
        else if(strPass.length() < 3)
        {
            Prompt.showError("Password must be >= 3 characters");
            this.jPassword.requestFocus();
        }
        else if(!strPass.equals(strConfirm))
        {
            Prompt.showError("Passwords must be the same");
            this.jPassword.requestFocus();
        }
        else
        {
            this.parent.getClient().doCreateAccount(strUsername, strPass, new NetMessageHandler()
            {
                @Override
                public void onDataReceived(String strAction, Connection objConnection, NetMessage objMsg)
                {
                    NetData objData = objMsg.getData();
                    Object obj = objData.getObject();

                    try
                    {
                        User objUser = (User) obj;
                        CreateAccountForm.this.parent.setUser(objUser);
                        CreateAccountForm.this.parent.showPanel("Login");

                        Prompt.showDialog("Account created successfully");
                    }
                    catch(ClassCastException e)
                    {
                        try
                        {
                            UserExistsException objUserExistsEx = (UserExistsException) obj;
                            Prompt.showError("Username taken!");
                        }
                        catch(ClassCastException ex)
                        {
                            ex.printStackTrace();
                        }
                    }
                }
            });
        }
    }//GEN-LAST:event_jCreateAccountButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jChitChatLogo;
    private javax.swing.JLabel jConfirmPassLabel;
    private javax.swing.JPasswordField jConfirmPassword;
    private javax.swing.JButton jCreateAccountButton;
    private javax.swing.JLabel jInfoLabel;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JLabel jPasswordLabel;
    private javax.swing.JTextField jUsername;
    private javax.swing.JLabel jUsernameLabel;
    // End of variables declaration//GEN-END:variables
}
