package com.chitchat.client.components.gui;

import com.chitchat.components.*;
import com.chitchat.components.net.*;
import com.chitchat.components.user.*;
import com.chitchat.client.components.Client;

import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import utilx.Prompt;

public class LoginForm extends ChitChatPanel {
    private static final int WIDTH = 350;
    private static final int HEIGHT = 185;

    private final MainGUI parent;

    /**
     * Creates new form LoginForm
     *
     * @param objParent The parent, a <code>MainGUI</code>
     */
    public LoginForm(MainGUI objParent) {
        initComponents();
        this.parent = objParent;
    }

    /**
    * Gets the desired width of this panel
    *
    * @return The desired width
    */
    public int getWidth()
    {
        return LoginForm.WIDTH;
    }

    /**
    * Gets the desired height of this panel
    *
    * @return The desired height
    */
    public int getHeight()
    {
        return LoginForm.HEIGHT;
    }

    /** An event fired when the panel is shown */
    public void onShow()
    {
        this.jUsername.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInfoLabel = new javax.swing.JLabel();
        jChitChatLogo = new javax.swing.JLabel();
        jUsernameLabel = new javax.swing.JLabel();
        jUsername = new javax.swing.JTextField();
        jPasswordLabel = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jLoginButton = new javax.swing.JButton();
        jCreateAccountButton = new javax.swing.JButton();

        jInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jInfoLabel.setText("Please log in or create an account");

        jChitChatLogo.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jChitChatLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jChitChatLogo.setText("chit chat");

        jUsernameLabel.setText("Username");

        jPasswordLabel.setText("Password");

        jLoginButton.setText("Login");
        jLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButtonActionPerformed(evt);
            }
        });

        jCreateAccountButton.setText("Create Account");
        jCreateAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jChitChatLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPassword)
                    .addComponent(jUsername)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jCreateAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLoginButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jChitChatLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginButton)
                    .addComponent(jCreateAccountButton)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCreateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateAccountButtonActionPerformed
        this.parent.showPanel(MainGUI.PANEL_CREATE_ACCOUNT);
    }//GEN-LAST:event_jCreateAccountButtonActionPerformed

    private void jLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonActionPerformed
        Prompt.setUseDialogs(true);
        String strUsername = this.jUsername.getText();
        String strPassword = new String(this.jPassword.getPassword());

        if(strUsername.length() < 3)
        {
            Prompt.showError("Username must be >= 3 characters");
            this.jUsername.requestFocus();
        }
        else if(strPassword.length() < 3)
        {
            Prompt.showError("Password must be >= 3 characters");
            this.jPassword.requestFocus();
        }
        else
        {
            try
            {
                //User objUser = this.parent.getServerConnection().doLogin(strUsername, strPassword);
                //Client.doLogin(strUsername, strPassword);
                //this.parent.setUser(objUser);
                this.parent.getClient().doLogin(strUsername, strPassword, new NetMessageHandler()
                {
                    @Override
                    public void onDataReceived(String strAction, Connection objConnection, NetMessage objMsg)
                    {
                        NetData objData = objMsg.getData();
                        Object obj = objData.getObject();

                        try
                        {
                            UserException objUserEx = (UserException) obj;

                            try
                            {
                                UserNotFoundException objNotFoundEx = (UserNotFoundException) objUserEx;

                                Prompt.showError("User not found!");
                                LoginForm.this.jUsername.requestFocus();
                            }
                            catch(ClassCastException ex)
                            {
                                try
                                {
                                    InvalidPasswordException objInvalidPassEx = (InvalidPasswordException) objUserEx;

                                    Prompt.showError("Invalid password!");
                                    LoginForm.this.jPassword.requestFocus();
                                }
                                catch(ClassCastException exx) {}
                            }
                        }
                        catch(ClassCastException e) {}

                        try
                        {
                            User objUser = (User) obj;
                            LoginForm.this.parent.setUser(objUser);
                            LoginForm.this.parent.showPanel(MainGUI.PANEL_MESSAGE_ROOM);
                        }
                        catch(ClassCastException e) {}
                    }
                });
            }
            catch(UserNotFoundException e)
            {
                Prompt.showError("User '" + strUsername + "' not found");
            }
            catch(InvalidPasswordException e)
            {
                Prompt.showError("Password is incorrect");
            }
        }
    }//GEN-LAST:event_jLoginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jChitChatLogo;
    private javax.swing.JButton jCreateAccountButton;
    private javax.swing.JLabel jInfoLabel;
    private javax.swing.JButton jLoginButton;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JLabel jPasswordLabel;
    private javax.swing.JTextField jUsername;
    private javax.swing.JLabel jUsernameLabel;
    // End of variables declaration//GEN-END:variables
}
