DROP TABLE users;

CREATE TABLE users
(
	id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
	username VARCHAR(32) NOT NULL,
	password VARCHAR(32) NOT NULL,
	admin BOOLEAN NOT NULL,
	UNIQUE(username)
);